### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by OrdinarySK** [pierrebaudot/infotopopy#3] opened 2020-09-30 08:17 UTC
Hello, I want to calculate multivariate joint entropies about 80 sites which contains three parameter. My sample data is follow:
precipitation | lst | soilmoisture
-- | -- | --
228 | 12.8923 | 8.04612
245 | 12.1109 | 6.95139
281 | 11.2158 | 10.6917
225 | 5.90652 | 7.37776
262 | 6.30347 | 9.76893
361 | 8.00681 | 9.26292
606 | 14.35 | 11.7481
231 | 4.61978 | 4.34707
510 | 10.8987 | 7.08284
One row is a site, I need to calculate multivariate sites's joint entropies. Can I use the package. Could you tell me how to use this package to calculate the values. If not, Could you give me some suggestions to solve the problem. Thank you.
I used the "infotopo" ,but always happens error when I import the package of "infotopo".

**Comment by pierrebaudot** [comment] 2020-09-30 16:25
Hello,
Thanks for notifying! There has been major reorganization of the package since 8 days and they are not all good or yet functional. I reverted to the previous working version. It shall work now (tell me if it does so that the issue can be closed). The pacakge will allow you to compute the Joint-entropies of H(precipitation, lst, solmoisture) but also of all the pairs like H(precipitation, moisture).... and the mutual informations etc.  For this, just follow the tutorial: 
https://infotopo.readthedocs.io/en/latest/basic_methods.html
You will have to install using (in command line in your environement):
pip install infotopo

then prepare your 80*3 matrix dataset  as data in a python script.

then set the parameters (you may check different values of nb_of_values) :
```
dimension_max =data.shape[1]
dimension_tot = data.shape[1]
sample_size = data.shape[0]
nb_of_values =9
forward_computation_mode = False
work_on_transpose = False
supervised_mode = False
sampling_mode = 1
deformed_probability_mode = False
```

then import the package and initialise-build infotopo
```
import infotopo
information_topo = infotopo.infotopo(dimension_max = dimension_max,
                            dimension_tot = dimension_tot,
                            sample_size = sample_size,
                            work_on_transpose = work_on_transpose,
                            nb_of_values = nb_of_values,
                            sampling_mode = sampling_mode,
                            deformed_probability_mode = deformed_probability_mode,
                            supervised_mode = supervised_mode,
                            forward_computation_mode = forward_computation_mode)
```

then compute jonit and marginals entropy and display them using:
```
Nentropie = information_topo.simplicial_entropies_decomposition(data)
information_topo.entropy_simplicial_lanscape(Nentropie)
```

do the next procedure to have mutual informations and so on

**Comment by OrdinarySK** [comment] 2020-10-06 01:44
Thank you very much. I will do it your way.

**Comment by pierrebaudot** [comment] 2020-10-06 01:46
tell me if it works, such that I can close the issue.

**Comment by OrdinarySK** [comment] 2020-10-06 02:16
I **pip install infotopo** , I still get an error when I import the package(**import infotopo**) in the Pycharm[No module named infotopo]. But the package was indeed downloaded and installed to my local library.

**Comment by OrdinarySK** [comment] 2020-10-09 12:18
So, can I use the infotopo package normally now?

**Comment by ganapathyramanathan** [comment] 2020-12-27 01:38
i am experiencing the same problem. i used google colab . but when i used import infotopo, i am getting the same error message. will be very much grateful to you if you could find a solution to the same. i was very much impressed with the results shown in the infotopo documentation.

**Comment by ganapathyramanathan** [comment] 2020-12-27 02:33
i tried to install using python3 setup.py install. i got the following error message:
ModuleNotFoundError: No module named 'setuptools'

**Comment by pierrebaudot** [comment] 2020-12-27 10:57
Dear,
Yes, I could reproduce the problem... and it is likely in the setup.py. I tried to fix it for some hours, but as of now my efforts failed. I will try again, but currently undergoe an overload of work. So, the way to use infotopo now is to download the infotopo.py and to make it run directly with your scripts. (notably all the examples in the documentation are in the __main__ as unitary test). I appology for this unconvenient use.

**Comment by pierrebaudot** [comment] 2022-04-11 22:29
The setup.py bug was fixed thanks to renxida.

**Closed as completed** 2022-04-11 22:28 UTC
